### ISSUE TITLE
Is the upper limit in Random.nextIntBetween supposed to be inclusive?

### ISSUE THREAD

**Issue by ajaychandran** [Effect-TS/io#281]
At present, `Random.nextIntBetween` [returns](https://github.com/Effect-TS/io/blob/4e5a886f4669931de00feff4426d6301e48cb127/src/internal_effect_untraced/random.ts#L47) an integer in the closed interval `[min, max]`.

The underlying implementation uses [data/Random](https://github.com/Effect-TS/data/blob/c114ccc316038e9276c380db79b17ff36cfdb044/src/Random.ts#L144) that returns an integer in the half-open interval `[0, max)`.

Also, the corresponding function in [ZIO](https://github.com/zio/zio/blob/c4a3d4045e83b802551481b5dd561518419c8e7c/core/shared/src/main/scala/zio/Random.scala#L34) returns an integer in the half-open interval `[min, max)`. In fact, upper bounds in all functions are considered exclusive.

**Comment by mikearnaldi** [comment]
we should pick either inclusive or exclusive and propagate it across all range-like functions I think we had picked inclusive so I am surprised it's exclusive in data/Random

**Comment by ajaychandran** [comment]
I think upper bounds should be exclusive. 
Both, `Math.random` and `data/Random.next` return a value in `[0.0, 1.0)`.

Another issue with having both lower and upper limits is that `max - min` could exceed the maximum value. For example, `nextRange` will return `Infinity` when this happens.
Unless there is a safer way to generate values in these cases, it might be better to default `min` to `0` and only have a `max` argument. This is the typical use case anyway.

**Comment by mikearnaldi** [comment]
cc @tim-smart we should probably tackle this as part of api standardization (I'd vote for half-open interval)
