### ISSUE TITLE
`opCodes/configError"' has no exported member 'OP_SOURCE_UNAVAILABLE'.` etc

### ISSUE THREAD

**Issue by leighman** [Effect-TS/io#324]
### Current Behavior

When installing I get a number of TS compilation errors
```
node_modules/@effect/io/Config/Error.d.ts:94:28 - error TS2694: Namespace '"/blah/node_modules/@effect/io/internal_effect_untraced/opCodes/configError"' has no exported member 'OP_SOURCE_UNAVAILABLE'.

94     readonly _tag: OpCodes.OP_SOURCE_UNAVAILABLE;
```

### Expected behavior

I would expect no compilation errors from the library

### Your environment

Didn't try below 0.6.0

| Software      | Version(s) |
| ------------- | ---------- |
| @effect/schema |       v0.6.0-v0.8.0     |
| TypeScript    |      4.9.5      |

**Comment by IMax153** [comment]
@mikearnaldi - given that our build process in-lines the op codes anyways, we should probably just consider removing op codes entirely.

**Comment by IMax153** [comment]
@leighman - I believe this should be closed by https://github.com/Effect-TS/io/commit/985dca4cd210baa4e066af4a43b35b1a43502090 once released. Going to close this issue. Thanks for the report!

**Comment by stazz** [comment]
@IMax153 Would it make sense to add a step into CI/CD pipeline, which would try to compile a simple TypeScript file, which would just `import` the `.d.ts` code produced by compilation of the source code in this repo? That would help to avoid similar errors in the future. At least I use similar approach in my own libraries, and it has helped me catching few similar errors to this one.

I can open separate ticket for that if you think that's good idea. Maybe even make a PR :)

**Comment by IMax153** [comment]
Thanks @stazz! Personally I don't think it's 100% necessary. We're pretty careful about only exposing things from the library that are going to end up in the declaration files.

That being said - I'll leave it up to @mikearnaldi for the final word.
