### ISSUE TITLE
Effect.tapFinally

### ISSUE THREAD

**Issue by floydspace** [Effect-TS/io#395]
Hi guys

I'm implementing something like disposing step in my program, like so:
```ts
  const whateverRecords = await pipe(
    Effect.tryPromise(() => MongoClient.connect(config.mongodbUrl)),
    Effect.flatMap((client) =>
      pipe(
        Effect.sync(() => client.db()),
        Effect.flatMap((db) =>
          Effect.tryPromise(() =>
            db
              .collection("whatever")
              .find()
              .toArray()
          )
        ),
        Effect.tapBoth(
          () => Effect.tryPromise(() => client.close()),
          () => Effect.tryPromise(() => client.close())
        )
      )
    ),
    Effect.runPromise
  );
```
is `Effect.tapBoth` a correct place where I close my connection, the problem here I'm forced to define 2 duplicate functions.
Does it make sense to implement something like `Effect.tapFinally`, or there is some alternative that I can use more seamlessly?

Thank you.

**Comment by floydspace** [comment]
@IMax153 Thank you very much, exactly what I need, pure joy to learn this, especially scopes, but the learning curve is so steep.

**Comment by IMax153** [comment]
> the learning curve is so steep.

Indeed, we are working on adding content to our [documentation site](https://www.effect.website) to help with the learning curve. But you can also drop questions here on GitHub or [in our Discord](https://discord.gg/effect-ts).
