### ISSUE TITLE
Effect.all what to do

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/io#429]
We've been playing with the idea of a single `Effect.all` api for a while but I can't seem to be able to make it work well for both the pipeable and non pipeable cases.

I have a few options:
- restrict `Effect.all` to use overloads such that direct usage works like: `Effect.all([a. b])`, `Effect.all(a, b)`, `Effect.all({ a, b })` and add `Effect.iterable(x)` for `Iterable<Effect> => Effect<Array>`
- hope and pray that TS improves inference of overloads (in the iteration plan) knowing that there's a good chance that it won't land as it may break half the world (but also may not, and would be the best design)
- rollback to our old nomenclature where we distinguish between tuple / struct and iterables

**Comment by patroza** [comment]
I think option 1 and 2 combined; bet on 1 for now, and once 2 comes around, consider in a major update?

**Comment by pigoz** [comment]
I agree. `.all` naming has so much better discoverability.

**Comment by alex-dixon** [comment]
I am using pipeable only for now as I feel it’s closer to where most programs and programmers are at than generators.

If ”all” doesn’t infer correctly for some cases I am used to (and ok with) falling back to more constrained variants (ie struct variant for a struct type) to narrow the possibilities of what can be inferred in Typescript or more exactly match the particular type I’m dealing with.

**Comment by mikearnaldi** [comment]
> I am using pipeable only for now as I feel it’s closer to where most programs and programmers are at than generators.
> 
> If ”all” doesn’t infer correctly for some cases I am used to (and ok with) falling back to more constrained variants (ie struct variant for a struct type) to narrow the possibilities of what can be inferred in Typescript or more exactly match the particular type I’m dealing with.

depends from the perspective, yes generators are uncommon in JS but async-await is well known and it isn't a big leap saying `await x -> yield* $(x)`

**Comment by jessekelly881** [comment]
I actually prefer option 3. In part because it matches the current syntax for Either, Option, etc. but more importantly it's clearer what the resulting type is and allows supporting multiple different resulting types(it seems clearer that it's actually a combinator). On the other hand.. my preference probably comes from experience with fp-ts, and all does seem more beginner friendly.

**Comment by tim-smart** [comment]
An updated `Effect.all` api has been added. If you encounter issues open another issue :)
