### ISSUE TITLE
Function arguments

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/io#437]
I've always felt the inner need to compact code but I am not that sure it's the best in all the cases, we should have a bit of a "vote" about:

```ts
import { pipe } from "@effect/data/Function"
import * as Effect from "@effect/io/Effect"

const randomResult = Effect.suspend(() => Math.random() > 0.5 ? Effect.fail("err") : Effect.succeed("ok"))

// current

export const program1 = Effect.matchCauseEffect(
  randomResult,
  (cause) => Effect.logErrorCause(cause),
  (str) => Effect.logInfo(str)
)

export const program1pipeable = pipe(
  randomResult,
  Effect.matchCauseEffect(
    (cause) => Effect.logErrorCause(cause),
    (str) => Effect.logInfo(str)
  )
)

// proposed

export const program2 = Effect.matchCauseEffect2(randomResult, {
  onFailure: (cause) => Effect.logErrorCause(cause),
  onSuccess: (str) => Effect.logInfo(str)
})

export const program2pipeable = pipe(
  randomResult,
  Effect.matchCauseEffect2({
    onFailure: (cause) => Effect.logErrorCause(cause),
    onSuccess: (str) => Effect.logInfo(str)
  })
)
```

and generally about any function that takes `>1` arguments except the `self`.

**Comment by mikearnaldi** [comment]
Note that this is actually possible because inference of records got significantly better in recent commits (should be done in TS 5.2)

For example:

```ts
export const hello = Effect.whileLoop2({
  check: () => true,
  body: () => Effect.succeed(0),
  process: (a) => Effect.log(`a: ${a}`)
})
```

This would priorly infer `a` to be `unknown` instead now it correctly infers `number` from the `body` step

**Comment by patroza** [comment]
My general rule of thumb is 2-3 arguments max, then the last should be an options argument.

For these basic match functions, it's a tough call.. after a short time you develop an intuition to the arguments.
But sure, while more verbose it is also more clear.
C#'s argument labels are kinda nice as you can then opt-in when you think it is more clear.
OTOH it also means it's messy as people call the methods in different ways.

**Comment by tsteckenborn** [comment]
I'd vote for prioritizing clarity over conciseness. Autocompletion tools aid quick typing, but clear cues significantly improve first-time readability and work understandability without tooling.

**Comment by datner** [comment]
>[...] after a short time you develop an intuition to the arguments.
But sure, while more verbose it is also more clear.
C#'s argument labels are kinda nice as you can then opt-in when you think it is more clear.
OTOH it also means it's messy as people call the methods in different ways.

I wholeheartedly agree. But there is a clear preference for 'named arguments' in js (in the form of the proposed object) in the ts/js sphere, and this allows potential (probably not very needed but still) flexibility in api.

I think that object notation is better over-all

**Comment by mikearnaldi** [comment]
> EDIT:
> It is important to note that object notation 'ruins' skim-reading because you can't build intuition around what the first function caught in my eye is this or that

please articulate what you mean by ` object notation 'ruins' skim-reading `

**Comment by datner** [comment]
@mikearnaldi 
using the object notation, this is valid:
```ts
export const program2 = Effect.matchCauseEffect2(randomResult, {
  onFailure: (cause) => Effect.logErrorCause(cause),
  onSuccess: (str) => Effect.logInfo(str)
})

export const program2pipeable = pipe(
  randomResult,
  Effect.matchCauseEffect2({
    onSuccess: (str) => Effect.logInfo(str),
    onFailure: (cause) => Effect.logErrorCause(cause)
  })
)
```
for a trivial case like this, the mental overhead of parsing which is the `onSuccess` and which is the `onFailure` is practically nothing. But for more complicated functions, it can make me stop skim-reading to make sure the effect I'm reading happens on the hook I think it does.

```ts
export const program1 = Effect.matchCauseEffect(
  randomResult,
  (cause) => Effect.logErrorCause(cause),
  (str) => Effect.logInfo(str)
)

export const program1pipeable = pipe(
  randomResult,
  Effect.matchCauseEffect(
    (cause) => Effect.logErrorCause(cause),
    (str) => Effect.logInfo(str)
  )
)
```

in this case, for ever know that the first is failure and the second is success without actually reading the code. Which allows skim-reading.
This is potentially a small issue, I still prefer the object notation, but flow-controls do benefit from intuition where option objects traditionally do not.

**Comment by mikearnaldi** [comment]
> @mikearnaldi using the object notation, this is valid:
> 
> ```ts
> export const program2 = Effect.matchCauseEffect2(randomResult, {
>   onFailure: (cause) => Effect.logErrorCause(cause),
>   onSuccess: (str) => Effect.logInfo(str)
> })
> 
> export const program2pipeable = pipe(
>   randomResult,
>   Effect.matchCauseEffect2({
>     onSuccess: (str) => Effect.logInfo(str),
>     onFailure: (cause) => Effect.logErrorCause(cause)
>   })
> )
> ```
> 
> for a trivial case like this, the mental overhead of parsing which is the `onSuccess` and which is the `onFailure` is practically nothing. But for more complicated functions, it can make me stop skim-reading to make sure the effect I'm reading happens on the hook I think it does.
> 
> ```ts
> export const program1 = Effect.matchCauseEffect(
>   randomResult,
>   (cause) => Effect.logErrorCause(cause),
>   (str) => Effect.logInfo(str)
> )
> 
> export const program1pipeable = pipe(
>   randomResult,
>   Effect.matchCauseEffect(
>     (cause) => Effect.logErrorCause(cause),
>     (str) => Effect.logInfo(str)
>   )
> )
> ```
> 
> in this case, I forever know that the first is failure and the second is success without actually reading the code. Which allows skim-reading. This is potentially a small issue, I still prefer the object notation, but flow-controls do benefit from intuition where option objects traditionally do not.

Got it, you mean arguments can be swapped, this is also kind of a feature & a bug at the same time, the order will matter if one argument is dependent on an inferred argument of another.

**Comment by TylorS** [comment]
For what it's worth I do like the readability of the object notation, but as a primarily FE dev I care a *lot* about my bundle sizes, and I do worry about having a lot of objects that won't minify as well as when things are just functions. The object keys usually can't be minified AFAIK since its a contract with the function itself. 

I agree with @patroza, I'd usually make 3 arguments, including the data, to be my maximum number of arguments before I do switch to some kind of options object. So at least in this example using `Effect.matchCauseEffect` I wouldn't bother making the changes, but for something like `Cause.match` I'd definitely appreciate the options object to cover the 7 different cases it currently has.

**Comment by mikearnaldi** [comment]
> For what it's worth I do like the readability of the object notation, but as a primarily FE dev I care a _lot_ about my bundle sizes, and I do worry about having a lot of objects that won't minify as well as when things are just functions. The object keys usually can't be minified AFAIK since its a contract with the function itself.
> 
> I agree with @patroza, I'd usually make 3 arguments, including the data, to be my maximum number of arguments before I do switch to some kind of options object. So at least in this example using `Effect.matchCauseEffect` I wouldn't bother making the changes, but for something like `Cause.match` I'd definitely appreciate the options object to cover the 7 different cases it currently has.

There are two arguments to consider:

1) how common is usage of multi arguments functions, most of the code uses flatMap/map/etc that are all single param, 2 or more arise only when you have an amount of conditionality (fail/succeed, while/loop, etc), and in that case being able to know just by reading what branch we are in is probably wanted

2) you are right object arguments cannot be tree-shaken but tree shaking is only one of the weapons used to improve data transit between backend and frontend, the other element is compression, code with repetition can be compressed more efficiently (compression primarily leverages more compact representation of redundant data)

So I think I would like to see the issue at play before considering it heavily, also there are other things we have to do to improve minification for example unboundling the fiber not to use class methods (and generally avoid class methods) when not necessary (or pre-minify them and have a by-index access)

**Comment by tim-smart** [comment]
I vote for the object API, as I think the increase in clarity is worth more than the object allocation (and these API's are few and far between, maybe ones like `Option.match` being the exception)

This will also provide a fix for some of the crazy `dual` signatures we have due to no support for optional arguments.

**Comment by IMax153** [comment]
I agree with @tim-smart - using object notation will allow us to improve the signatures of a large number of methods which currently require multiple implementations to support optional args. For example, the `Effect.log*` variants could be compacted significantly.

**Comment by datner** [comment]
>`Cause.match`

I didn't even notice this one, what a horrendous signature 😆

**Comment by mikearnaldi** [comment]
It depends by how we define the number of parameters, the rule should be to wrap in an object any function with >1 parameter except from self. Like for example `mapBoth` would use an object and `map` would not. De facto this would make all the dual functions have respectively 1 (when pipeable) and 2 (when data first) args.

**Comment by IMax153** [comment]
So there would effectively be two rules:

## Constructors

Constructors with `>=1` function argument would use an object to take all parameters. For example:

```ts
declare const tryCatchPromise: <E, A>(params: {
  try: LazyArg<Promise<A>>,
  onReject: (reason: unknown) => E
}) => Effect<never, E, A>
```

## Methods

Methods with `>=3` parameters (including `self`) will have all parameters other than `self` wrapped as an object.

```ts
// 2 arguments including self
export const map: {
  <A, B>(f: (a: A) => B): <R, E>(self: Effect<R, E, A>) => Effect<R, E, B>
  <R, E, A, B>(self: Effect<R, E, A>, f: (a: A) => B): Effect<R, E, B>
}

// 3 arguments including self
export const mapBoth: {
  <E, A, E2, A2>(params: {
    onError: (e: E) => E2, 
    onSuccess: (a: A) => A2
  }): <R>(self: Effect<R, E, A>) => Effect<R, E2, A2>
  <R, E, A, E2, A2>(
    self: Effect<R, E, A>, 
    params: {
      onError: (e: E) => E2, 
      onSuccess: (a: A) => A2
    }
  ): Effect<R, E2, A2>
}
```

**Comment by IMax153** [comment]
For those who land here in the future - here is the proposal we are going with for now.

https://github.com/Effect-TS/io/issues/437#issuecomment-1580868282

I will keep this issue open until we complete the related work.

**Comment by patroza** [comment]
oh boy, you guys must be bored or something :D

**Comment by tim-smart** [comment]
> So there would effectively be two rules:

I think this should have exceptions. Methods like `Effect.bind`, `Effect.updateService` become less clear IMO when using an Object api.

**Comment by IMax153** [comment]
As we encounter them, we can document them and note relevant exceptions.

**Comment by alex-dixon** [comment]
Would this be a breaking change?

In general I prefer named/object arguments. But in the examples above, the left/right semantics of something like match leverage existing well known patterns and conventions (error-first callbacks etc). I could see it as clearer for newcomers but would wonder what other places require knowledge of that convention (if a goal is to remove the need to know it).

**Comment by mikearnaldi** [comment]
> Would this be a breaking change?
> 
> In general I prefer named/object arguments. But in the examples above, the left/right semantics of something like match leverage existing well known patterns and conventions (error-first callbacks etc). I could see it as clearer for newcomers but would wonder what other places require knowledge of that convention (if a goal is to remove the need to know it).

Yes it is a breaking change

**Comment by adrian-gierakowski** [comment]
Just wanted to check if consensus has been reached on this topic and if the decision was to go ahead, how long would it take to migrate all core effect libraries to the new interface. It’s a bit difficult to push for adoption with such a drastic change on the horizon. Or maybe this would only affect a small % of available library functions?

**Comment by pigoz** [comment]
> Or maybe this would only affect a small % of available library functions?

Most functions are below 3 arguments (including self).

**Comment by tim-smart** [comment]
Closing as complete, as #461 has merged.
