### ISSUE TITLE
Stack Tracing

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/io#438]
The back story of stack tracing is long, but let's start with a quick explainer on what is the goal.

Let's say you have a program like:

```ts
import { pipe } from "@effect/data/Function"
import * as Effect from "@effect/io/Effect"

declare const doA: () => void
declare const doB: () => void

export const program = pipe(
  Effect.sync(() => doA()),
  Effect.flatMap(() => Effect.sync(() => doB()))
)
```

And let's assume we don't expect `doA` or `doB` to potentially throw but as we all know we discover in the worst way that they indeed have a bug that blows up.

When you run the code without any tracing facility you will get a plain JS stack trace of where the error is thrown from (that could be deeply nested inside `doA`) and you then get a bunch of completely useless frames pointing to FiberRuntime.runLoop where the function is invoked from.

By default you don't get any pointer to the `Effect.sync(() => doA/B())` calls that and that makes debugging hard.

## Historical Solution
- via typescript transform plugin, add `@traced` (or similar) to the definition of `sync` and the code becomes: `withTrace(location)(Effect.sync(() => doA()))`
- via typescript transform plugin, add `__trace` as the last argument and the code becomes `Effect.sync(() => doA(), location)`

## Current Solution
- all effect functions create a `new Error()` when invoked and carry that error object inside, to limit costs we both limit the stack frames of the `new Error()` generated and have a system that once you are in a function that has a trace nested traces are skipped.

## Problems with Current Solution
- when functions are used tacitely the trace is still broken, i.e. `pipe(f, Effect.sync, Effect.forever)`
- while `new Error()` is a JS standard the `stack` field generation is not and runtimes have different formats
- it requires source maps to work, without source maps you get messy errors
- the `stackTraceLimit` config on the Error prototype is a standard in V8, others are following but there is no guarantee
- in node you still need to enable source maps explicitly and bare the added cost
- browsers and bundlers and frameworks complexify everything, even if you get to setup source map correctly the maps are only processed by the dev tools leading to:
![Screenshot 2023-05-22 140814](https://github.com/Effect-TS/io/assets/24249610/332a62ab-aaff-4da5-a7af-58abda5e86ff)
- when tracing is fully disabled there is still a ~3x cost due to the region-based logic that enables disabling tracing for nested cases that ends up wrapping code with `restore(f)(x)`

## Advantages
- in debug / dev mode it usually works out of the box and you get nice and complete error traces
- with bits of pain you can get good traces in backend
- no compiler plugin needed, especially not a ts plugin that depends on types

## Conclusion
After all the research and feedback from users I am not sure I like the current solution, it doesn't seem to help in the way that it was supposed to help and it is costly (while not too costly, it still adds up).

## Path forward
We have been working on native span based tracing (like open telemetry), while **it is not aimed at the exact same target** we can use span data to provide a stack like message in the error, it requires diligence from the user perspective of writing code like:

```ts
import { pipe } from "@effect/data/Function"
import * as Effect from "@effect/io/Effect"

declare const doA = Effect.withSpan("doA")(
  Effect.sync(() => potentiallyFailingA())
)
declare const doB: = Effect.withSpan("doB")(
  Effect.sync(() => potentiallyFailingB())
)

export const program = Effect.withSpan("program")(
  pipe(
    doA,
    Effect.flatMap(() => doB)
  )
)
```

and any error will include the path to root (cut at n levels) of spans like:

```
program > doA:
  message bla bla from error
  ... potentially native error stack if present
```

the same code will also provide full tracing to exporters when configured so that the spans created provide full telemetry for your app code.

Of course one wouldn't need to annotate every single effect but rather "bite sized" blocks of code, it won't point exactly to where the error is generated but will be "close enough" to be debugged without too much effort.

**Comment by patroza** [comment]
What about traced vs non traced builds? Like react prod vs non prod build etc.

**Comment by mikearnaldi** [comment]
> What about traced vs non traced builds? Like react prod vs non prod build etc.

leads to many different issues and leads to the developer having to painfully configure module aliases for every package, also it isn't really clear how to have package X that depends on Y depend on Y traced if X traced and on Y untraced if X is untraced, also it will require heavy plugins that most likely will need to depend on type information - out of scope.

also to be clear: it's not even clear how to remove tracing given it's really produced via normal function calls, i.e. you can't remove all calls to `restore`

**Comment by mattiamanzati** [comment]
Spans are great.
Also ideally automatic spans can be eventually added by any type-aware middleware, either eslint or ttsc if the user really want so to every declaration/exported symbol

**Comment by mikearnaldi** [comment]
> Spans are great. Also ideally automatic spans can be eventually added by any type-aware middleware, either eslint or ttsc if the user really want so to every declaration/exported symbol

Great point that I forgot to add, via plugins we can allow every effect returning function & constant of a specific set of files (identified via regex, name convention, whatever) to define an implicit span, potentially even without type info at the price of a small runtime check

**Comment by evelant** [comment]
It would also be excellent if you could add annotations to spans for errors just like logging. For example `Error in DbServer > saveModel: Error message` is useful but `Error in DbServer > saveModel: Error message (modelName: "foo") (modelId: "123-asdf")` is massively more useful since it reveals not just where and error happened but also the relevant state/context that may have caused it.

**Comment by antoine-coulon** [comment]
I also like the span idea, this is more or less what I'm already using (in a simplified way without stack/context propagation) to deal with telemetry and I find it pretty convenient. IMHO it offers both flexibility from a user-land perspective to be in charge of defining more or less granular spans and can also be enhanced/added via plugins afterwards. 

Also, because they are also meant to be exported for external tools, they would most likely help solving many problems at once.

**Comment by mikearnaldi** [comment]
> Given I mostly use Effect in a browser, I've run across this issue quite a bit where the stack traces are nearly useless to me. I find myself missing the compile-time traces that were once there.
> 
> I think it'd be really useful to have a compile-time plugin again. That said, I don't have a strong preference on whether or not there are native traces or if they utilized native spans as long as they're reported nicely inside of a pretty-printed cause. I'd assume spans would have the additional benefit of being able to create a lot more information besides just traces and being able to be exported to external tools, so maybe spans are the way to go since it'd condense 2 ideas into the more powerful of the 2.

Yeah a plugin could easily transform `Effect.withSpan("name")(x)` to `Effect.withSpan("name", { location })(x)` to enhance the span with the location, that's doable even without type information to a good extent

**Comment by IMax153** [comment]
@mikearnaldi - I'd like to move this discussion towards a resolution, so here are my two cents after working with native traces. I'll provide my preference for a direction forward first, and then add several points why in no particular order.

I move that we immediately begin removing native tracing from all Effect codebases and begin work on productionizing integrations for the span-based solution.

1. I have also found that in the majority of cases stack traces have not been useful to me when developing Effect library or application code. Instead, I find myself frequently reaching for the span-based tracing and seamless integration with external tooling such as OpenTelemetry.
2. For maintainers / contributors to the Effect codebase, implementing native tracing properly is an _extremely_ obtuse thing to wrap your head around. Removing them would improve the experience of maintainers / contributors as well as removing mental overhead.
3. The performance impact when native tracing is enabled is not negligible in a medium to large size Effect application. Though the performance of span-based tracing will arguably be similar, I think most people expect that when exporting spans to an external application.
4. I think a plugin / transform-based solution gives us the best of both worlds.

**Comment by mikearnaldi** [comment]
3. No, it would be way better. The reason the stack tracing is expensive is due to the wrapping in restore of every continuation and the generation of a ` new Error()` object. Neither apply for span base tracing so the overhead is negligible.

**Comment by IMax153** [comment]
> No, it would be way better

Even more of a reason to move ahead with the proposal to remove native tracing.

**Comment by patroza** [comment]
To me the native stack trace has been tremendously helpful, and i'm very happy we got them. 
It has helped a lot with error reports that we run over Sentry to help locate the issue and have basically parity with classic js stack traces.
Loosing this and going to have to sprinkle various spans through my code, is not something that sounds very attractive to me.
Stack traces and spans e.g for telemetry serve different things for me.

To really judge though, I think we need to look at some real world error stack trace differences between current, with first class stack trace support, and without stack trace support.

**Comment by aniravi24** [comment]
I completely agree with @patroza, proper stack traces have been awesome from an app development perspective, despite the downsides mentioned above.

I also agree that error stack traces are not something I usually associate with spans, and I'm curious to better understand what that looks like and how it might work.

Being able to report errors into Sentry or to clearly see error traces in local development with no additional code has been great. I suspect that making errors harder to find will cause a lot of friction for new users coming to Effect, unless I'm misunderstanding how it might work. Looking forward to better understanding the proposed changes!

**Comment by evelant** [comment]
Maybe it's broken on react-native because I'm not sure what "proper stack traces" are being referred to here. Any time I print a Cause I get something like this:

```
causePretty:
TypeError: Cannot convert undefined value to object
    at ?anon_0_ (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:173153:43)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:141435:35)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:122956:26)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:141436:15)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:122970:26)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:146156:19)
    at value (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:146853:42)
    at _loop2 (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:147067:35)
    at runLoop (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:147090:28)
    at _loop (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:146652:40)
    at evaluateEffect (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:146688:18)
    at evaluateMessageWhileSuspended (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:146629:34)
    at drainQueueOnCurrentThread (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:146458:118)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:146227:40)
    at starveInternal (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:138405:19)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:138424:40)
    at tryCallOne (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:29382:26)
    at _callTimer (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:29301:17)
    at _callReactNativeMicrotasksPass (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:29331:17)
    at callReactNativeMicrotasks (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:29494:44)
    at __callReactNativeMicrotasks (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:2413:46)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:2225:45)
    at __guard (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:2397:15)
    at flushedQueue (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:2224:21)
    at invokeCallbackAndReturnFlushedQueue (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:2218:33)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:173126:17)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:223256:90)
    at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false:223258:30)

```

**Comment by patroza** [comment]
<img width="1366" alt="Screenshot 2023-06-13 at 09 00 19" src="https://github.com/Effect-TS/io/assets/42661/1d9f2602-de6f-464e-a1a4-ced400be1c20">
Here's at least a non Effect sample of an error report from a Vue frontend.
Im not sure I understand how uploading source maps affects filtering things out later. can you link me to code?

**Comment by mikearnaldi** [comment]
> Here's at least a non Effect sample of an error report from a Vue frontend. <img alt="Screenshot 2023-06-13 at 09 00 19" width="1366" src="https://user-images.githubusercontent.com/42661/245380569-1d9f2602-de6f-464e-a1a4-ced400be1c20.png">
> 
> @mikearnaldi Im not sure I understand how uploading source maps affects filtering things out later. can you link me to code?
> 
> Trying to make some time for a repro repo

https://github.com/Effect-TS/data/blob/d29ca9bac94377f7a6b95f9ee86edc4deb46ee26/src/Debug.ts#L116

Anything non effect related is irrelevant. Effect tracing needs runtime access to the sourcemapped location, unless you get that working it's not going to be helpful

**Comment by TylorS** [comment]
There's a project I played around with once many years ago that does this - https://github.com/xpl/stacktracey. It doesn't seem too active today, but maybe there's something to learn from it

**Comment by mikearnaldi** [comment]
> @TylorS I also played with stacktracey in an attempt to get useful stacks out of react-native in dev. It somewhat worked, I got excellent error stacks and logging locations, but there was a massive performance hit from parsing the maps in-client and it doesn't work at all on the hermes runtime. Processing source maps inside of effect like stacktracey could probably work but seems like it might be impractical due to performance and js engine limitations.

After investigation I can confirm that it would add fairly large overhead and be extremely complex to maintain properly, I think it may be added to a "debug" mode where spans also carry source locations

**Comment by IMax153** [comment]
Closing this issue as it has been decided that native stack tracing will be removed in favor of span-based solutions. This is to accomplish the following:

1. Enhance maintainability
2. Improve efficiency of Effect programs
3. Avoid confusing stack traces when source maps are not included
