### ISSUE TITLE
Add `getCached` function to `Cache` module

### ISSUE THREAD

**Issue by evelant** [Effect-TS/io#443]
@IMax153 

It would be useful to have a utility function on Cache for "get cached value if it exists in the cache, otherwise none"

Pseudocode for workaround to do this:
```ts
const getCached = <T>(someCache, key): Effect<never, never, Option<T>> =>
 pipe(
   someCache.contains(key),
   T.ifEffect(
     //remove E since we know it's cached, the lookup fn won't get called so E is impossible
     pipe(cache.get(key), T.map(O.some), T.catchTags(...)), 
     T.succeedNone()
   )
)
```

**Comment by IMax153** [comment]
Closing as completed by #445

**Comment by evelant** [comment]
@IMax153 Why does the signature for `getOption` include `Error`?  Since it will never hit the resolver function shouldn't it be `Effect<never, never, Option.Option<Value>>` instead?

```ts
 /**
     * Retrieves the value associated with the specified key if it exists.
     * Otherwise returns `Option.none`.
     */
    getOption(key: Key): Effect.Effect<never, Error, Option.Option<Value>>;
```

**Comment by tim-smart** [comment]
The error is there because a cache entry can still be in a pending state, in the case where the lookup effect is async.

If the cache entry is in a pending state, then it will await the underlying Deferred and pass any errors back to the caller.

**Comment by evelant** [comment]
@tim-smart OK makes sense. Perhaps there's a need for another function then. A sort of `getImmediateOption` that will run sync without any Error only returning the entry if it's actually already cached, ignoring any pending.

I think that may be the more useful behavior. The current `getOption` is basically just a shorthand for the following.

```ts
pipe(
   someCache.contains(key),
   T.ifEffect(
     pipe(cache.get(key), T.map(O.some)), 
     T.succeedNone()
   )
```

AFAIK there's no way to do a `getImmediateOption` with the current Cache api. I think it would be useful for situations where you want to take different actions based on whether a value is _immediately_ available because a pending cache request could take an arbitrary amount of time to complete.

**Comment by tim-smart** [comment]
Yes I don't see an issue with another API for getting a completed cache value.

```ts
readonly getComplete: (key: Key) => Effect<never, never, Option<Value>>
```

**Comment by IMax153** [comment]
Closing as completed by #448
