### ISSUE TITLE
Invalid Type for Tags with Layers

### ISSUE THREAD

**Issue by ikollipara** [Effect-TS/io#538]
I'm currently trying to create a simple Express Server with Layers and such, but currently I'm getting thrown an annoying type error, where The `Context.Tag` doesn't comply with what `Layer` expects.

```ts
import * as Effect from "@effect/io/Effect";
import * as Context from "@effect/data/Context";
import * as Layer from "@effect/io/Layer";
import express, { type Express } from "express";

const App = Context.Tag<Express>();

export const AppLive = Layer.succeed(App, express());
```

![Screenshot from 2023-07-14 21-41-20](https://github.com/Effect-TS/io/assets/36077619/8bb7544f-b0fb-4248-bfb0-4a2a9e2c96bc)

My current versions of `@effect/io` and `@effect/data` are: 
```json
"@effect/data": "^0.15.0",
"@effect/io": "^0.32.2"
```

**Comment by gcanti** [comment]
Downgrade `@effect/data` to `0.14.3` or remove both `@effect/*` packages and install `npm i effect@latest` which is now the recommended way https://www.effect.website/docs/quickstart

**Comment by ikollipara** [comment]
Okay! Thank you! I had it installed before that change. It's all working now.
