### ISSUE TITLE
Feature request: Multi-arg flatMap

### ISSUE THREAD

**Issue by jessekelly881** [Effect-TS/io#615]
It's very common (at least in the code I write) to have multiple Effect.flatMap chains. It would be very useful to extend the flatMap function to help reduce boilerplate. 

```ts
Effect.flatMap( // Effect<..., C>
    Effect<..., A>
    (a: A) => Effect<..., B>,
    (a: B) => Effect<..., C>,
    // etc...
)
```

**Comment by fubhy** [comment]
Overloading an api with alternative syntax for the same things should generally be avoided unless there's a real benefit to it. In this case, I'm doubtful that adding built-in pipe-like behavior to `flatMap` (or any other operator) would be beneficial. In my opinion, this'd negatively impact readability and composability.

```ts
Effect.flatMap( // Effect<..., C>
    Effect<..., A>
    (a: A) => Effect<..., B>,
    (a: B) => Effect<..., C>,
    // etc...
)
```

vs.

```ts
pipe(
  // ...
  Effect.flatMap(...),
  Effect.flatMap(...),
  Effect.flatMap(...),
  // etc...
)
```

I personally prefer the latter.

**Comment by jessekelly881** [comment]
```ts
pipe(
  Effect.flatMap((fs) => fs.readFileString(`${__dirname}/test.json`)),
  Effect.flatMap(S.parse((ParseJson))),
  Effect.flatMap(JsonSchema.decodeSchema),
  Effect.flatMap(JsonSchema.toFile),
  Effect.flatMap(formatCode),
  Effect.flatMap(writeFileString(`${__dirname}/../test.ts`))
)
```
